package org.jalvarez.jsf.entities;

import jakarta.persistence.*;

import java.util.Objects;

// Marks this class as a JPA entity, which maps to a database table
@Entity
@Table(name = "categorias") // Specifies the database table name for this entity
public class Categoria {


    @Id // Marks this field as the primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // Specifies that the primary key is auto-generated by the database
    private Long id;

    private String nombre; // Represents the name of the category


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Override
    public boolean equals(Object o) {
        // Checks if the current object is equal to another object
        if (this == o) return true; // Returns true if both references point to the same object
        if (o == null || getClass() != o.getClass()) return false; // Ensures the other object is of the same class
        Categoria categoria = (Categoria) o;
        // Compares the IDs to determine equality
        return Objects.equals(id, categoria.id);
    }
}
